### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by DavidGriffith** [btolab/hypseus#2]
I successfully compiled Hypseus and got it launching Dragon's Lair using my run.sh script (slightly modified) from https://github.com/DavidGriffith/daphne.  I get sound and the controls seem work, but I'm getting a plain black (white after shifting virtual desktops) screen/window for the video.

This looks really nice.  If I can get past these nits, I'll drop my Daphne fork and work on this instead.

**Comment by h0tw1r3** [comment]
FYI this should be fixed with https://github.com/btolab/hypseus/pull/6
Testing tonight myself. Please have a look if possible.
