### ISSUE TITLE
Compile Pi4 Fails

### ISSUE THREAD

**Issue by 2play** [btolab/hypseus#35]
As per read me both git clone and tar source fail with

`Scanning dependencies of target video
[  8%] Building CXX object video/CMakeFiles/video.dir/video.cpp.o
In file included from /home/pi/code/hypseus-1.3.0/src/video/video.h:29,
                 from /home/pi/code/hypseus-1.3.0/src/video/video.cpp:36:
/home/pi/code/hypseus-1.3.0/src/video/SDL_FontCache.h:37:10: fatal error: SDL_ttf.h: No such file or directory
 #include "SDL_ttf.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [video/CMakeFiles/video.dir/build.make:63: video/CMakeFiles/video.dir/video.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:719: video/CMakeFiles/video.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....` 

Best I got was at 26% by setting 
`CFLAGS="-O3 -march=armv8-a+crc+simd -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard" CXXFLAGS="-O3 -march=armv8-a+crc+simd -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard"`

`[ 26%] Building CXX object video/CMakeFiles/video.dir/video.cpp.o
In file included from /home/pi/code/hypseus-1.3.0/src/video/video.h:29,
                 from /home/pi/code/hypseus-1.3.0/src/video/video.cpp:36:
/home/pi/code/hypseus-1.3.0/src/video/SDL_FontCache.h:37:10: fatal error: SDL_ttf.h: No such file or directory
 #include "SDL_ttf.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [video/CMakeFiles/video.dir/build.make:63: video/CMakeFiles/video.dir/video.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:719: video/CMakeFiles/video.dir/all] Error 2
make: *** [Makefile:106: all] Error 2
`

Any ideas?

**Comment by DirtBagXon** [comment]
`No such file or directory #include "SDL_ttf.h"` is your clue.

Try this compile for RPi:  https://github.com/DirtBagXon/hypseus-singe/blob/master/RETROPIE.md

**Comment by 2play** [comment]
Thank you @DirtBagXon 
I will do this morning and reply. Guide is very straightforward!

**Comment by 2play** [comment]
You are the man! Thank you for the kind support!
All work great and I use hypseus even as its own emu setup
